### PR TITLE
Port from GObject to Glib

### PR DESCRIPTION
**Pull request by ayushnawal**
tested

### CODE REVIEW

**Review by srevinsaju — CHANGES_REQUESTED** [review]
Tested on Sugar DE, Sugar Live Build Debain 0.116. @ayushnawal probably you missed out these errors, guess these are related to your port.
```
/media/HDD/repo/turtlepond/game.py:167: Warning: Source ID 8589 was not found when attempting to remove it
  GLib.source_remove(self._timeout_id)
```

PS: Is it related to #10 ?

**Comment by ayushnawal** [comment]
@srevinsaju i have resolved this warning already in #10 , actually, I already did this port in another branch so I made a different pull request.

**Comment by srevinsaju** [comment]
Ok, I will recheck after merging both branches :)

**Comment by quozl** [comment]
Thanks.  Reviewed.

**Pull request merged**
