### PR TITLE
source_remove warnings

### LINKED ISSUE #9: source_remove warnings
```log
/usr/share/sugar/activities/TurtleinaPond.activity/game.py:167: Warning: Source ID 12324 was not found when attempting to remove it
  GObject.source_remove(self._timeout_id)
```

### PR DESCRIPTION
**Pull request by ayushnawal**
Fixes #9

### CODE REVIEW

**Comment by quozl** [comment]
Yes, that will fix it.

Also needs GObject to GLib conversion of the timeout_add and source_remove functions.

It is unusual code and has another small fault; the turtle dance animation stutters because a new timeout is scheduled at the time the previous timeout is finishing.  Each time there is a small delay, it grows.  You'll see how the call to timeout_add happens inside the function.  The function also does not explicitly return True or False as it should, instead just an ordinary `return`, which has the effect of False.  It is more correct to use a repeating timeout, that way the function is more likely to be called some multiple of 250ms after the first call.

**Comment by ayushnawal** [comment]
Thanks. already made a pull request for GObject to GLib with a flake8 pr.

> It is unusual code and has another small fault; the turtle dance animation stutters because a new timeout is scheduled at the time the previous timeout is finishing. Each time there is a small delay, it grows. You'll see how the call to timeout_add happens inside the function. The function also does not explicitly return True or False as it should, instead just an ordinary return, which has the effect of False. It is more correct to use a repeating timeout, that way the function is more likely to be called some multiple of 250ms after the first call.

trying to fix the stuttering and delay, will update you

**Comment by quozl** [comment]
Reviewed 12b1960 again.  It misses the mark.  Another reason may be when `_happy_turtle_dance` returns early.  Thus `self._timeout_id` would still be set but GLib would not have the event source registered.

**Comment by chimosky** [comment]
Closing as this has been fixed in 843e726.

**Pull request closed without merging**
